### ISSUE TITLE
Breakpoint types conversion 

### ISSUE THREAD

**Issue by kenborge** [elqteam/elq#46]
Currently the code that adds support for breakpoints of different types (em, px, rem) are located in the elq-breakpoints-plugin. Having this in the plugins means that every other plugin that want's to implement a different approach to generating the breakpoints need to implement this functionality as well. 

Currently it looks to me like a breakpoint is defined as ```{dimension, pixelValue, value, type}```. Would it not make more sense to do the conversion in the breakpoint-state-calculator and simplify a breakpoint to ```{dimension, value, type}```

**Comment by wnr** [comment]
> Currently the code that adds support for breakpoints of different types (em, px, rem) are located in the elq-breakpoints-plugin. Having this in the plugins means that every other plugin that want's to implement a different approach to generating the breakpoints need to implement this functionality as well.

I think a nice solution to this would be to split up the retrieving of the breakpoints (getting the dimension, value and type) and the interpretation/calculation of such breakpoints into two separate plugins. This way, many plugins may exist that fetches the breakpoints of an element (e.g., the current attributes API `elq-breakpoints-widths="300px"` vs an imaginary javascript API `plugin.setBreakpoints(element, { width: ["300px"]})`). Such plugins could then be freed from having to interpret the type (e.g., px, em) and instead just pass it to the elq instance. The elq instance could then in turn have many different breakpoint type plugins registered (e.g., px, em, rem. But could also include custom types and dimensions such as ratios, color, etc. This way we don't limit different implementations of interpreting breakpoint types/dimensions, and make it possible to add new types/dimensions via plugins instead of having to bump the core library.

> Currently it looks to me like a breakpoint is defined as {dimension, pixelValue, value, type}. Would it not make more sense to do the conversion in the breakpoint-state-calculator and simplify a breakpoint to {dimension, value, type}

Yes, this is something that needs to be reworked with the new system proposed above. I think the simplification would be a nice addition.

**Comment by kenborge** [comment]
Does elq detect arbitrary style changes? It would have to trigger on more then just element size changes for it to make sense to add support for other types like color and such. 

With a system like the one you propose, all plugins should probably be moved out of the main project. In fact that should probably be done now as well. I'm not using any of the default plugins for instance.

**Comment by wnr** [comment]
> Does elq detect arbitrary style changes? It would have to trigger on more then just element size changes for it to make sense to add support for other types like color and such.

Not at the moment, but with the proposed solution I hope that the plugins may implement such detectors. I think it would be great if arbitrary element properties could be targeted for the element queries.


> With a system like the one you propose, all plugins should probably be moved out of the main project. In fact that should probably be done now as well.

Indeed. I do think its wise to provide a bundle with the most basic plugins registered so that basic users do not need to hassle with plugins (as jquery and bootstrap does). But I think it would be nice to also have a bare-bone file which users would need to registered all plugins to be used by themselves. Much like React does with its `react.js` and `react-with-addons.js`.

> I'm not using any of the default plugins for instance.

That's interesting, because we are not either at the moment :) Instead of writing conditional CSS we are altering the HTML structure in our application. We have created a React component called ResponsiveBlock that handles ELQ for us, so that the children of the component just needs to care about a size property (e.g., small, medium, large) and then style itself accordingly. The ResponsiveBlock component listens to the `elq.listenTo(element, "breakpointStatesChanged", callback)` event in order to update the size property accordingly. How do you use it? :)

**Comment by kenborge** [comment]
I have a plugin that sounds kinda similar to yours but using angular.
You put a directive on a parent component and gives it and "ID". This html element then gets classes added to it of the same type you are using(small, medium, large). So if the element is over the small breakpoint for that component it gets the class ```elq-<id>-small``` etc.

It also reads the breakpoints from a JSON config that is read into SASS so one can use a eql breakpoint mixin.
```json
{
  "eql": {
    "<id>": {
      "small": "",
      "medium": "",
      "large": "",
    }
  }
}
```

**Comment by wnr** [comment]
I see, very interesting! Would love to see more of your usage :)

**Comment by wnr** [comment]
We now have a idea of a solution for v2, and the type conversion has been moved into the core until v2.
