### ISSUE TITLE
Elq resize detector causing horizontal scroll

### ISSUE THREAD

**Issue by kenborge** [elqteam/elq#57]
The elq resize detector is causing out pages to have horizontal scroll when a container that is elq activated are using 100% screen width. This is because the elq scroll detector element that it inserted in into the activated element has a negative margin that makes it overflow the parent element. What is the reason for this negative margin? From the looks of the code the margin is equal to the scrollbar width, but the element doesn't have any scrollbars.

**Comment by wnr** [comment]
Hi!

We too encountered this issue today, and opened an issue about it in the element-resize-detector subproject: https://github.com/wnr/element-resize-detector/issues/40

The injected element needs to be at least 1x1px in size in order to detect scroll events, and is therefore per default 1 pixel bigger in each dimension of the targeted element (since the targeted element may be 0x0 px). When the system has scrollbars activated (windows behavior default) we still want to have at least 1px of scroll area and therefore the size of the scrollbars are accounted for. The inserted element does not have scrollbars, but the containing ones do have.

We've found a simple solution to this problem, which I'll try out today.

If you want to fix your issues temporarily, you can wrap the target element with a `div style="overflow: hidden>".

**Comment by kenborge** [comment]
Not sure if i got you right but do you mean you had the same issue but that the scroll element is overflowing the container by just 1 px? Because for us it's overflowing the container element by the scrollbar width + 1px basically. So the scroll detector is basically 30px wider and higher then the container

**Comment by kenborge** [comment]
For now i just fixed it by doing 
```
//Quick fox for elq resize detectors pushing out the page with negative margins
.erd_scroll_detection_container {
    left: 0 !important;
    right: 0 !important;
    top: 0 !important;
    bottom: 0 !important;
}
```

**Comment by wnr** [comment]
I meant that we experience the same issue that you are (overflowing 1px + scrollbar * 2), the second paragraph was to explain why the injected element has negative top/left properties from the beginning :)

I would go with the `overflow:hidden` approach instead, as I'm pretty sure that setting those values to 0 will break if the targeted element may be small.

**Comment by kenborge** [comment]
Alright will it be fine to put `overflow: hidden` on the element that is elq activated, or does it have to be an element that is wrapping it?

**Comment by wnr** [comment]
The one that is elq-activated should be fine.

**Comment by wnr** [comment]
Unbelievable, the reason why we are experiencing this problem in our project is because we accidentally used the old 0.3 version instead of the new 0.4.1! Switching to the new version solved our issues :D

I guess that this issue will too be resolved if you upgrade.

**Comment by kenborge** [comment]
Seems to work on new version yes. Though I could no longer recreate it on the forked version we use either.... So who knows
