### ISSUE TITLE
Not possible to disable bundled plugins 

### ISSUE THREAD

**Issue by kenborge** [elqteam/elq#59]
It's currently not possible to disable the bundled breakpoint state serializer plugin, without disabling apply breakpoint states which disables all plugins from having the apply function called. This is an issue if you use custom plugins that have a lot of breakpoints the element gets super crowded with classes, and it's a lot of unnecessary code run. on breakpoint changes

**Comment by wnr** [comment]
Hmm interesting. I guess one solution would be to not use the default serializer plugin (to use the `elq-without-plugins.js` and then register the wanted plugins. Then the default plugins need to be exported to the `dist` map as well so that they can be combined freely. This solution would however be insufficient if it is desired to disable specific plugins only in some cases...

Perhaps a better approach is to provide an API to disable/enable plugins both globally and locally for elements. The custom plugin could then override the default plugin by disabling it for the given element. What do you think?

**Comment by kenborge** [comment]
So we actually use the default plugins on some element, but custom plugins on other elements. So we can't not include the default plugins. But it should be possible to indicate pr element what plugins you want to use. For our custom plugin we do this by having the plugin set a boolean flag when the element is activated on the elq config for that element if the plugin attribute was set on the element.

**Comment by wnr** [comment]
Indeed. Could you share some example code of your usage so that I can see if the coming API is sufficient for such use case?

I'm thinking about having an elq config that says the default plugins to be enabled/disabled, and then a possibility to enable/disable on per-element activation.

**Comment by kenborge** [comment]
You mean of the plugin implementation?

This is teh activate function for a plugin called elq-component, it sets the elqModule config to true to indicate that this element should use the plugin, so the get breakpoints and apply state functions check that elq.eqlModule is set to true or they return

`function activate(element) {
    var el = angular.element(element);
    if (!el.attr('elq-component')) {
       return;
    }

    //elq options
    element.elq.resizeDetection = true;
    element.elq.updateBreakpoints = true;
    element.elq.applyBreakpoints = true;
    element.elq.cycleCheck = true;

    //private options
    element.elq.elqModule = true;
    el.addClass('elq-' + el.attr('elq-component'));
}`

**Comment by wnr** [comment]
Okay thanks :)
